name: Captains
main: com.publicuhc.captains.CaptainsPlugin
version: 1.0
description: Captains draft mode
author: ghowden/Eluinhost
commands:
  startdraft:
    description: Start draft mode
    usage: /<command> [-t=team_size] [-f] player1,player2,player3,player4,player5
    aliases: [captainsstartdraft]
  pick:
    description: Pick a player
    usage: /<command> player_name
    aliases: [captainspick]
  picklist:
    description: List all unpicked players
    usage: /<command>
    aliases: [captainspicklist]
  enddraft:
    description: Forces the draft to end
    usage: /<command>
    aliases: [captainsenddraft]
  addpick:
    description: Adds a player to the pick list
    usage: /<command> player_name
    aliases: [captainsaddpick]
  removepick:
    description: Removes a player from the pick list
    usage: /<command> player_name
    aliases: [captainsremovepick]
permissions:
  captains.draft.start:
    description: Allows usage of the start draft command
    default: op
  captains.draft.start:
    description: Allows usage of the end draft command
    default: op
  captains.draft.addpick:
    description: Allows usage of the add pick command
    default: op
  captains.draft.removepick:
    description: Allows usage of the remove pick command
    default: op
  captains.draft.pick:
    description: Allows usage of the pick command (restricted to captains in draft stage)
    default: true
  captains.draft.pick:
    description: Allows usage of the picklist command
    default: true
  captains.draft.spectate:
    description: Won't be considered as online for usage in the plugin (immune to picks, captain, not count to player count in draft start)
    default: false